== ProPra Abschlussprojekt

=== Anmerkungen zum Programm

==== Starten

Die Anwendung kann mit 'docker-compose up --build' gebaut werden,
danach mit 'docker-compose up' gestartet werden.

==== Data-Faker

Beim ersten Start des Programms wird die Datenbank mit Dummy-Daten
gefüllt um den Initialprozess abzukürzen. +
Das Passwort für alle Dummy Nutzer ist: 123 +
Mögliche Usernames mit Role user: jackeline.rath, annamae.mohr, cora.cartwright
Admin-Account: admin , Admin-Password: 123

Es werden zudem Contracts zwischen Usern erstellt.
Bei jackeline.rath findet man zudem eine seit langem fällige
Abgabe, bei der man auch das Banner sehen kann.
Sollte ProPay zum Programmstart nicht gestartet sein, so werden
zwar die Fake-User erstellt, allerdings wird ihnen kein Guthaben hinzugefügt
und es werden keine Contracts erstellt.

==== User-Erstellung

Es können neue Nutzer erstellt werden, dies geschieht über den 'Sign up'
Button.

==== Main Page

Auf der main-Page werden alle ausleihbaren Items angezeigt.
Über einen Button links oben kann man auf die Seite
der kaufbaren Items gelangen.
Hier kommt der User auch auf sein Profil und es gibt die Navbar.

==== Profile page

Die Profile Page des Users enthält alle Infos zu jeglichen:

* User Details = Profilbild und Details zum Nutzer
* Own Items = eigene Items (offene Anfragen akzeptieren)
* Borrowed Items = vom User ausgeliehene Items
* Lent Items = Items vom User, welche verliehen sind
* Sold/Bought = verkaufte/gekaufte Items
* Requests = vom User gestellt Anfragen
* Options = erstellen neuer Items, bearbeiten der Kontodaten
* ProPay Settings = Details zu Propay Guthaben und Auflademöglichkeit

* (only admin) Admin = Button zur Overview aller offenen Konflikte

==== Konflikte

Konflikte werden nicht vom Data-Faker erstellt. Diese werden über die
Profile Page eröffnet, indem man auf den entsprechenden Contract klickt. +
Die anzeigen verändern sich entsprechend vorliegender Konflikte.
Der Admin bekommt alle offenen Konflikte angezeigt, sobald er in seinem
Profil den Button dafür klickt. Er kann dann jeden einzelnen Konflikt
resolven:

* Free Bail = befreie Kaution, beende Contract
* Punish Bail = behalte Kaution ein, beende Contract
* Cancel Contract = beende Contract, keine Zahlungen erfolgen,
Reservierungen werden frei gegeben
* Continue Contract = contract läuft ganz normal weiter

Der Admin hat für jeden Konflikt alle Möglichkeiten, da ihm vertraut wird,
zu wissen was er tun muss.

==== Bilder hochladen

Der Nutzer kann Profil-/Itembilder hochladen. Technische Schulden
siehe arc42 Doku.

==== Haupt Dokumentation

Die Haupt Dokumentation befindet sich im arc42 Ordner des Github-Rpositories.


