[[section-introduction-and-goals]]
==	Einführung und Ziele


Bei dem vorliegenden Projekt soll eine Webanwendung im Rahmen eines
Universitären Praktikums erstellt werden.
Die Bearbeiter/Entwickler sind hierbei die Mitglieder der achter-Gruppe
bugrog-morgoth-ush-parse
namentlich(in alphabetischer Reihenfolge)
Christian, Ingo, Jonathan, Lars, Markus, Philipp, Sami und Stefan.

Die Stakeholder im Rahmen des Projekts sind die Aufgaben/Projektsteller.
In der Realität gäbe es allerdings noch weitere Stakeholder, diese sind unter 'Stakeholder'
aufgeführt.

Mindest "Geschäftsziel" ist es hierbei die in der gegebenen Aufgabenstellung mitgelieferten
User-Stories, Use-Caseses und genannten Mindestanforderungen zu erfüllen.

Die Aufgabenstellung ist dabei die Erstellung einer Webanwendung welche
es registrierten und angemeldeten Nutzern ermöglichen soll eigene Gegenstände
einzustellen und dadurch anderen Nutzern zum Verleih anzubieten. Ebenso möglich
muss es sein eine Leihe über die Detailseite des eingestellten Gegenstandes anzufragen.

Ferner soll es eine Konfliktlösestelle durch einen Admin der Seite geben welcher
bei Problemen mit den geliehenen Gegenständen über die Seite eingeschaltet werden
können soll.

Zusätzlich zu der gegebenen Aufgabenstellung ist durch Modifikation in der letzten
Woche noch hinzu gekommen, dass die Webanwendung neben Verleih auch Kauf von Gegenständen
ermöglichen soll. Hierdurch ist auch ein weiterer Aspekt der Aufgabenstellung
deutlich geworden. Die gewählte Softwarearchitektur soll/muss nämlich leicht wart/-und
erweiterbar sein.

Weitere generelle Ziele sind eine gute Benutzbarkeit der Oberfläche. Dies
inkludiert eine aufgeräumte, übersichtliche und schnell reagierende Oberfläche.


=== Stakeholder


[cols="1,1,2" options="header"]
|===
|Rolle |Kontakt |Erwartungshaltung
| Verkäufer/Verleiher | UserRepo | Verleihen / Verkaufen von eigenen Geräten, Gegenständen
| Käufer/Leiher | UserRepo | Einfaches ausleihen und kaufen von Geräten.
| Admin | UserRepo | Lösen von Konflikten zwischen den Usern
| Entwickler | Github | Entwickelung der Applikation, einfache Erweiterbarkeit
| Betreiber der Applikation | - | Günstiger betrieb, hoher Gewinn, viele Nutzer

|===
