[[section-introduction-and-goals]]
==	Einführung und Ziele


Bei dem vorliegenden Projekt soll eine Webanwendung im Rahmen eines
Universitären Praktikums erstellt werden.
Die Bearbeiter/Entwickler sind hierbei die Mitglieder der achter-Gruppe
bugrog-morgoth-ush-parse
namentlich(in alphabetischer Reihenfolge)
Christian, Ingo, Jonathan, Lars, Markus, Philipp, Sami und Stefan.

Die Stakeholder im Rahmen des Projekts sind die Aufgaben/Projektsteller.

Mindest "Geschäftsziel" ist es hierbei die in der gegebenen Aufgabenstellung mitgelieferten
User-Stories, Use-Caseses und genannten Mindestanforderungen zu erfüllen.

Die Aufgabenstellung ist dabei die Erstellung einer Webanwendung welche
es registrierten und angemeldeten Nutzern ermöglichen soll eigene Gegenstände
einzustellen und dadurch anderen Nutzern zum Verleih anzubieten. Ebenso möglich
muss es sein eine Leihe über die Detailseite des eingestellten Gegenstandes anzufragen.

Ferner soll es eine Konfliktlösestelle durch einen Admin der Seite geben welcher
bei Problemen mit den geliehenen Gegenständen über die Seite eingeschaltet werden
können soll.

Zusätzlich zu der gegebenen Aufgabenstellung ist durch Modifikation in der letzten
Woche noch hinzu gekommen, dass die Webanwendung neben Verleih auch Kauf von Gegenständen
ermöglichen soll. Hierdurch ist auch ein weiterer Aspekt der Aufgabenstellung
deutlich geworden. Die gewählte Softwarearchitektur soll/muss nämlich leicht wart/-und
erweiterbar sein.

Weitere generelle Ziele sind eine gute Benutzbarkeit der Oberfläche. Dies
inkludiert eine aufgeräumte, übersichtliche und schnell reagierende Oberfläche.



=== Aufgabenstellung

[role="arc42help"]
****
.Inhalt
Kurzbeschreibung der fachlichen Aufgabenstellung, treibenden Kräfte, Extrakt (oder Abstract) der Anforderungen.
Verweis auf (hoffentlich vorliegende) Anforderungsdokumente (mit Versionsbezeichnungen und Ablageorten).


.Motivation
Aus Sicht der späteren Nutzer ist die Unterstützung einer fachlichen Aufgabe oder Verbesserung der Qualität der eigentliche Beweggrund, ein neues System zu schaffen oder ein bestehendes zu modifizieren.

.Form
Kurze textuelle Beschreibung, eventuell in tabellarischer Use-Case Form.
Sofern vorhanden sollte die Aufgabenstellung Verweise auf die entsprechenden Anforderungsdokumente enthalten.

Halten Sie diese Auszüge so knapp wie möglich und wägen Sie Lesbarkeit und Redundanzfreiheit gegeneinander ab.
****

=== Qualitätsziele

[role="arc42help"]
****
.Inhalt
Die Top-3 bis Top-5 der Qualitätsziele für die Architektur, deren Erfüllung oder Einhaltung den maßgeblichen Stakeholdern besonders wichtig sind.
Gemeint sind hier wirklich Qualitätsziele, die nicht unbedingt mit den Zielen des Projekts übereinstimmen. Beachten Sie den Unterschied.


.Motivation
Weil Qualitätsziele grundlegende Architekturentscheidungen
oft maßgeblich beeinflussen, sollten Sie die für Ihre Stakeholder
relevanten Qualitätsziele kennen, möglichst konkret und
operationalisierbar.

Wenn Sie als Architekt nicht wissen, woran Ihre Arbeit gemessen wird, ....

.Form
Tabellarische Darstellung der Qualitätsziele mit möglichst konkreten Szenarien, geordnet nach Prioritäten.
****

=== Stakeholder


[cols="1,1,2" options="header"]
|===
|Rolle |Kontakt |Erwartungshaltung
| User | UserRepo | Nutzen der Applikation , Leihen / Kaufen
| Admin | UserRepo | Lösen von Konflikten
| Entwickler | Github | Entwickelung der Applikation

|===
