[[section-quality-scenarios]]
== Qualitätsanforderungen

[cols="5%,20%,75%",frame="topbot",options="header"]
|=======
|Nr | Qualitätsmerkmal | Umsetzung
|1  | Benutzerfreundlichkeit |  Sollte ein Benutzer was falsch machen oder z.B.
								der ProPay Server nicht erreichbar sein, dann
								soll der Benutzer eine Aussagekräftige
								Fehlermeldung bekommen.
|2  | Erweiterbarkeit | Wir haben oft unseren Code gerefactored und selbst
						kritisch analysiert, damit der Code einfach und
						Strukturiert bleibt. Ebenfalls ist es durch die
						Vererbung der **Item** und **Contract** Klassen
						einfach sinnvolle Erweiterungen zu implememntieren.
|3  | Security | Um gute Security zu gewährleisten haben wir auf eigene
				 Implementierung verzichtet und **Spring Security** verwendet.
				 Hinter **Spring Security** steht eine große Community, deshalb
				 ist eine bessere Security gegeben als eine eigene
				 Implementierung
|4  | Allgemeines Pay System | Es war das Payment System **ProPay** vorgegeben,
 							   allerdings wollte wir unsere Anwendung flexible
							   halten und haben ein Interface definiert für das
							   Payment System. Ebenfalls ist Anpassung auf ein
							   anderes Payment System relativ simple, da die
							   Struktur auf Änderungen ausgelegt ist.
|5  | Ansprechende View | Um eine halbwegs anständige View zu gewährleisten
						  haben wir uns für **Bootstrap** entschieden.
						  Ebenfalls hat sich jeder mit Bootstrap kurz
						  auseinandergesetzt und so ist eine anständige und
						  teilweise **responsive** View entstanden
|=======

[role="arc42help"]
****
.Inhalt
Dieser Abschnitt enthält möglichst alle Qualitätsanforderungen als Qualitätsbaum mit Szenarien.
Die wichtigsten davon haben Sie bereits in Abschnitt 1.2 (Qualitätsziele)
hervorgehoben.

Nehmen Sie hier auch Qualitätsanforderungen geringerer Priorität auf,
deren Nichteinhaltung oder -erreichung geringe Risiken birgt.


.Motivation
Weil Qualitätsanforderungen die Architekturentscheidungen
oft maßgeblich beeinflussen, sollten Sie die für Ihre Stakeholder
relevanten Qualitätsanforderungen kennen, möglichst konkret und
operationalisiert.

****


=== Qualitätsbaum

[role="arc42help"]
****
.Inhalt
Der Qualitätsbaum ( a la ATAM) mit Qualitätsszenarien an den Blättern.

.Motivation
Die mit Prioritäten versehene Baumstruktur gibt Überblick über die
oftmals zahlreichen Qualitätsanforderungen.

.Form
* Baumartige Verfeinerung des Begriffes „Qualität“, mit "Qualität" oder
Nützlichkeit als Wurzel.
* Mindmap mit Q-Oberbegriffen als Hauptzweige

In jedem Fall sollten Sie hier Verweise auf die Szenarien des folgenden
Abschnittes aufnehmen.
****



=== Qualitätsszenarien

[role="arc42help"]
****
.Inhalt
Konkretisierung der (in der Praxis oftmals vagen oder impliziten)
Qualitätsanforderungen durch (Qualitäts-)Szenarien.


Diese Szenarien beschreiben, was beim Eintreffen eines Stimulus auf ein
System in bestimmten Situationen geschieht.

Wesentlich für die meisten Softwarearchitekten sind zwei Arten von Szenarien:

*  Nutzungsszenarien (auch genannt Anwendungs- oder Anwendungsfallszenarien) beschreiben, wie das System zur Laufzeit auf einen
bestimmten Auslöser reagieren soll. Hierunter fallen auch Szenarien zur Beschreibung von Effizienz oder Performance.
Beispiel: Das System beantwortet eine Benutzeranfrage innerhalb einer Sekunde.
*  Änderungsszenarien beschreiben eine Modifikation des Systems oder seiner unmittelbarer Umgebung. Beispiel: Eine zusätzliche
 Funktionalität wird implementiert oder die Anforderung an ein Qualitätsmerkmal ändert sich.


.Motivation
Szenarien operationalisieren Qualitätsanforderungen und machen deren Erfüllung
mess- oder entscheidbar.

Insbesondere wenn Sie die Qualität Ihrer Architektur mit
Methoden wie ATAM überprüfen wollen, bedürfen die in Abschnitt 1.2
genannten Qualitätsziele einer weiteren Präzisierung
bis auf die Ebene von diskutierbaren und nachprüfbaren Szenarien.


.Form
Entweder tabellarisch oder als Freitext.

****
